"""Auditable MCP SDK — a protocol machine for tool self-attestation into a tamper-evident ledger.

This package is a pure protocol machine (canonicalization, hashing, signing, state transitions).
It carries no storage backend and no tool business logic; persistence is the integrator's concern,
supplied through the adapter interfaces this SDK defines.

The `spec_version` implemented is `auditable-mcp/0.3`. The MCP wire binding lives in the
`auditable_mcp.mcp` subpackage, which is the one part that needs the official `mcp` package.
"""

from auditable_mcp.canonical import (
    CONTEXT_HASH_PREFIX,
    MAX_SAFE_INTEGER,
    CanonicalizationError,
    canonicalize,
    has_unsafe_number,
    hash_canonical,
    sha256_hex,
)
from auditable_mcp.capability import (
    NegotiationOutcome,
    NegotiationResult,
    level_satisfies,
    negotiate,
    witness_satisfies,
)
from auditable_mcp.clock import Clock, SystemClock, now_iso
from auditable_mcp.decorator import auditable_tool, bound_session, current_session
from auditable_mcp.degradation import Posture, UnnegotiatedSessionError, transport_for
from auditable_mcp.hashing import GENESIS_HASH, compute_record_hash, witness_payload
from auditable_mcp.host import AuditHost, IntegrityAnomaly, SignatureVerifier, WitnessSigner
from auditable_mcp.in_process import InProcessTransport
from auditable_mcp.l2 import (
    BoundaryObserver,
    Ed25519Signer,
    Ed25519WitnessSigner,
    EgressObservation,
    KeyRegistry,
    KeyRegistryVerifier,
    KeyRole,
    ReconcileAnomaly,
    RegisteredKey,
    SignatureAlgorithm,
    ToolKey,
    WitnessRegistryVerifier,
    generate_tool_key,
    reconcile,
    sign_event,
    signature_payload,
    verify_detached_signature,
    verify_ecdsa_signature,
    verify_ed25519_signature,
)
from auditable_mcp.ledger import Ledger, SealedRecord
from auditable_mcp.models import (
    EXTENSION_ID,
    KNOWN_SPEC_VERSIONS,
    SPEC_VERSION,
    AbortReason,
    AcceptResponse,
    AttemptResponse,
    AuditCapability,
    AuditCapabilityInput,
    AuditEvent,
    Level,
    Outcome,
    RejectReason,
    RejectResponse,
    Status,
    TargetResource,
    UnavailableResponse,
    WireModel,
    Witness,
    first_sealed_validation_error,
    first_validation_error,
)
from auditable_mcp.session import (
    AmcpAbortedError,
    AmcpSession,
    AuditedAction,
    Deps,
    EventSigner,
    SystemDeps,
    WitnessVerifier,
)
from auditable_mcp.storage import InMemoryLedgerRepository, LedgerRepository, RepositoryError
from auditable_mcp.transport import (
    AuditEndpoint,
    AuditTransport,
    accept,
    reject,
    unavailable,
)
from auditable_mcp.verify import (
    DEFAULT_ADAPTER,
    RecordAdapter,
    SignatureChecker,
    VerifyIssue,
    VerifyReport,
    WitnessChecker,
    verify_chain,
    verify_ledger,
)

__version__ = '0.3.0'

__all__ = [
    '__version__',
    'AbortReason',
    'accept',
    'AcceptResponse',
    'AmcpAbortedError',
    'AmcpSession',
    'AttemptResponse',
    'auditable_tool',
    'AuditCapability',
    'AuditCapabilityInput',
    'AuditedAction',
    'AuditEndpoint',
    'AuditEvent',
    'AuditHost',
    'AuditTransport',
    'bound_session',
    'BoundaryObserver',
    'CanonicalizationError',
    'canonicalize',
    'Clock',
    'compute_record_hash',
    'CONTEXT_HASH_PREFIX',
    'current_session',
    'DEFAULT_ADAPTER',
    'Deps',
    'Ed25519Signer',
    'Ed25519WitnessSigner',
    'EgressObservation',
    'EventSigner',
    'EXTENSION_ID',
    'first_sealed_validation_error',
    'first_validation_error',
    'generate_tool_key',
    'GENESIS_HASH',
    'has_unsafe_number',
    'hash_canonical',
    'InMemoryLedgerRepository',
    'InProcessTransport',
    'IntegrityAnomaly',
    'KeyRegistry',
    'KeyRegistryVerifier',
    'KeyRole',
    'KNOWN_SPEC_VERSIONS',
    'Ledger',
    'LedgerRepository',
    'Level',
    'level_satisfies',
    'MAX_SAFE_INTEGER',
    'negotiate',
    'NegotiationOutcome',
    'NegotiationResult',
    'now_iso',
    'Outcome',
    'Posture',
    'reconcile',
    'ReconcileAnomaly',
    'RecordAdapter',
    'RegisteredKey',
    'reject',
    'RejectReason',
    'RejectResponse',
    'RepositoryError',
    'SealedRecord',
    'sha256_hex',
    'signature_payload',
    'sign_event',
    'SignatureAlgorithm',
    'SignatureChecker',
    'SignatureVerifier',
    'SPEC_VERSION',
    'Status',
    'SystemClock',
    'SystemDeps',
    'TargetResource',
    'ToolKey',
    'transport_for',
    'unavailable',
    'UnavailableResponse',
    'UnnegotiatedSessionError',
    'verify_chain',
    'verify_detached_signature',
    'verify_ecdsa_signature',
    'verify_ed25519_signature',
    'verify_ledger',
    'VerifyIssue',
    'VerifyReport',
    'WireModel',
    'Witness',
    'witness_payload',
    'witness_satisfies',
    'WitnessChecker',
    'WitnessRegistryVerifier',
    'WitnessSigner',
    'WitnessVerifier',
]
