"""Auditable MCP SDK — a protocol machine for tool self-attestation into a tamper-evident ledger.

This package is a pure protocol machine (canonicalization, hashing, signing, state transitions).
It carries no storage backend and no tool business logic; persistence is the integrator's concern,
supplied through the adapter interfaces this SDK defines.

The `spec_version` implemented is `auditable-mcp/0.3`. The MCP wire binding lives in the
`auditable_mcp.mcp` subpackage, which is the one part that needs the official `mcp` package.
"""

from auditable_mcp.canonical import (
    CONTEXT_HASH_PREFIX,
    MAX_SAFE_INTEGER,
    CanonicalizationError,
    canonicalize,
    has_lone_surrogate,
    has_unsafe_number,
    hash_canonical,
    sha256_hex,
)
from auditable_mcp.capability import (
    NegotiationOutcome,
    NegotiationResult,
    countersign_satisfies,
    level_satisfies,
    negotiate,
)
from auditable_mcp.clock import Clock, SystemClock, now_iso
from auditable_mcp.decorator import auditable_tool, bound_session, current_session
from auditable_mcp.degradation import Posture, UnnegotiatedCallError, transport_for
from auditable_mcp.hashing import GENESIS_HASH, compute_record_hash, countersignature_payload
from auditable_mcp.host import AuditHost, Countersigner, IntegrityAnomaly, SignatureVerifier
from auditable_mcp.in_process import InProcessTransport
from auditable_mcp.l2 import (
    REVOKED_MEMBER,
    ROLE_MEMBER,
    BoundaryObserver,
    CountersignatureRegistryVerifier,
    Ed25519Countersigner,
    Ed25519Signer,
    EgressObservation,
    KeyRegistry,
    KeyRegistryVerifier,
    KeyRole,
    ReconcileAnomaly,
    RegisteredKey,
    SignatureAlgorithm,
    ToolKey,
    assert_registries_disjoint,
    generate_tool_key,
    jwk_thumbprint,
    load_tool_key,
    public_jwk,
    public_key_of,
    reconcile,
    sign_event,
    signature_payload,
    tool_key_pkcs8,
    verify_detached_signature,
    verify_ecdsa_signature,
    verify_ed25519_signature,
)
from auditable_mcp.ledger import Ledger, SealedRecord
from auditable_mcp.models import (
    EXTENSION_ID,
    KNOWN_SPEC_VERSIONS,
    SPEC_VERSION,
    AbortReason,
    AcceptResponse,
    AttemptResponse,
    AuditCapability,
    AuditCapabilityInput,
    AuditEvent,
    AuditRequestMeta,
    AuditResultMeta,
    Countersign,
    Level,
    Outcome,
    RejectReason,
    RejectResponse,
    Status,
    TargetResource,
    UnavailableResponse,
    WireModel,
    first_sealed_validation_error,
    first_validation_error,
)
from auditable_mcp.session import (
    AmcpAbortedError,
    AmcpSession,
    AuditedAction,
    CountersignatureVerifier,
    Deps,
    EventSigner,
    SessionNumbering,
    SystemDeps,
    new_session_id,
)
from auditable_mcp.storage import InMemoryLedgerRepository, LedgerRepository, RepositoryError
from auditable_mcp.transport import (
    AmcpUsageError,
    AuditEndpoint,
    AuditTransport,
    accept,
    reject,
    unavailable,
)
from auditable_mcp.verify import (
    DEFAULT_ADAPTER,
    CountersignatureChecker,
    ExpectedIdentity,
    RecordAdapter,
    SignatureChecker,
    UnaccountedSignerSeq,
    VerifyIssue,
    VerifyReport,
    unaccounted_signer_seq,
    verify_chain,
    verify_ledger,
)

__version__ = '0.3.0'

__all__ = [
    'tool_key_pkcs8',
    'public_key_of',
    'public_jwk',
    'load_tool_key',
    'jwk_thumbprint',
    'REVOKED_MEMBER',
    'ROLE_MEMBER',
    '__version__',
    'AbortReason',
    'accept',
    'AcceptResponse',
    'AmcpAbortedError',
    'AmcpSession',
    'AmcpUsageError',
    'AttemptResponse',
    'auditable_tool',
    'AuditCapability',
    'AuditCapabilityInput',
    'AuditedAction',
    'AuditEndpoint',
    'AuditEvent',
    'AuditRequestMeta',
    'AuditResultMeta',
    'AuditHost',
    'AuditTransport',
    'bound_session',
    'BoundaryObserver',
    'CanonicalizationError',
    'canonicalize',
    'Clock',
    'compute_record_hash',
    'CONTEXT_HASH_PREFIX',
    'current_session',
    'DEFAULT_ADAPTER',
    'Deps',
    'Ed25519Signer',
    'Ed25519Countersigner',
    'EgressObservation',
    'EventSigner',
    'EXTENSION_ID',
    'first_sealed_validation_error',
    'first_validation_error',
    'generate_tool_key',
    'GENESIS_HASH',
    'has_lone_surrogate',
    'has_unsafe_number',
    'hash_canonical',
    'InMemoryLedgerRepository',
    'InProcessTransport',
    'IntegrityAnomaly',
    'KeyRegistry',
    'KeyRegistryVerifier',
    'KeyRole',
    'KNOWN_SPEC_VERSIONS',
    'Ledger',
    'LedgerRepository',
    'Level',
    'level_satisfies',
    'MAX_SAFE_INTEGER',
    'negotiate',
    'new_session_id',
    'NegotiationOutcome',
    'NegotiationResult',
    'now_iso',
    'Outcome',
    'Posture',
    'reconcile',
    'ReconcileAnomaly',
    'RecordAdapter',
    'RegisteredKey',
    'reject',
    'RejectReason',
    'RejectResponse',
    'RepositoryError',
    'SealedRecord',
    'sha256_hex',
    'signature_payload',
    'sign_event',
    'SignatureAlgorithm',
    'SignatureChecker',
    'SignatureVerifier',
    'SPEC_VERSION',
    'Status',
    'SystemClock',
    'SessionNumbering',
    'SystemDeps',
    'TargetResource',
    'ToolKey',
    'assert_registries_disjoint',
    'transport_for',
    'unavailable',
    'UnavailableResponse',
    'UnaccountedSignerSeq',
    'unaccounted_signer_seq',
    'UnnegotiatedCallError',
    'verify_chain',
    'verify_detached_signature',
    'verify_ecdsa_signature',
    'verify_ed25519_signature',
    'verify_ledger',
    'VerifyIssue',
    'VerifyReport',
    'WireModel',
    'Countersign',
    'countersignature_payload',
    'countersign_satisfies',
    'CountersignatureChecker',
    'ExpectedIdentity',
    'CountersignatureRegistryVerifier',
    'Countersigner',
    'CountersignatureVerifier',
]
