"""The MCP bindings: the §6 exchange on a real MCP connection (§6.4, §6.5).

Importing this subpackage requires the official `mcp` package, which the core does not: install
`auditable-mcp-sdk[mcp]`. Everything else in this SDK works over the abstract `AuditTransport` seam
and carries no transport dependency at all.
"""

from auditable_mcp.mcp.declaration import EXTENSIONS_MEMBER, audit_extension, capability_of, declare, declare_into
from auditable_mcp.mcp.http import (
    CONNECTION_CLOSED_MESSAGE,
    DEFAULT_FORWARD_TIMEOUT,
    DEFAULT_IDLE_TIMEOUT,
    FORWARD_OUTCOME_UNKNOWN_MESSAGE,
    FORWARDED_HEADER,
    FORWARDED_VALUE,
    MAX_QUEUED_NOTIFICATIONS,
    PRINCIPAL_MISMATCH_MESSAGE,
    REGISTRY_FULL_MESSAGE,
    SESSION_ALREADY_OPEN_MESSAGE,
    SESSION_BODY_PATH,
    SSE_PING_INTERVAL,
    AuditedStreamableHTTP,
    Forward,
    ForwardedRequest,
    ForwardedResponse,
    ForwardNotDeliveredError,
    ForwardOutcomeUnknownError,
    HttpForwarder,
    PrincipalOf,
    ToolServerFactory,
)
from auditable_mcp.mcp.seam import (
    AFFINITY_HEADER,
    ATTEMPT_METHOD,
    DEFAULT_REQUEST_TIMEOUT,
    DISCOVER_METHOD,
    ID_PREFIX,
    INITIALIZE_METHOD,
    INSTANCE_PATTERN,
    MAX_IDLE_SESSIONS,
    MAX_ROUNDS_PER_CALL,
    NO_OPEN_ROUND_MESSAGE,
    OUTCOME_METHOD,
    PROCESS_INSTANCE,
    RETRY_NOT_SENT_MESSAGE,
    ROUND_TOKEN_PREFIX,
    HandshakeNotSeenError,
    McpAuditCall,
    McpAuditReceiver,
    McpAuditTransport,
    McpBindingError,
    UnknownCallError,
    UnnegotiatedSendError,
    access_token_of,
    check_instance,
    negotiate_unaudited,
    new_instance_id,
    round_token_instance,
    with_affinity_header,
)

__all__ = [
    'access_token_of',
    'AFFINITY_HEADER',
    'ATTEMPT_METHOD',
    'AuditedStreamableHTTP',
    'audit_extension',
    'capability_of',
    'check_instance',
    'CONNECTION_CLOSED_MESSAGE',
    'declare',
    'declare_into',
    'DEFAULT_FORWARD_TIMEOUT',
    'DEFAULT_IDLE_TIMEOUT',
    'DEFAULT_REQUEST_TIMEOUT',
    'EXTENSIONS_MEMBER',
    'Forward',
    'FORWARD_OUTCOME_UNKNOWN_MESSAGE',
    'ForwardNotDeliveredError',
    'ForwardOutcomeUnknownError',
    'FORWARDED_HEADER',
    'FORWARDED_VALUE',
    'ForwardedRequest',
    'ForwardedResponse',
    'HandshakeNotSeenError',
    'HttpForwarder',
    'ID_PREFIX',
    'DISCOVER_METHOD',
    'INITIALIZE_METHOD',
    'INSTANCE_PATTERN',
    'MAX_IDLE_SESSIONS',
    'MAX_QUEUED_NOTIFICATIONS',
    'MAX_ROUNDS_PER_CALL',
    'McpAuditCall',
    'McpAuditReceiver',
    'McpAuditTransport',
    'McpBindingError',
    'negotiate_unaudited',
    'new_instance_id',
    'NO_OPEN_ROUND_MESSAGE',
    'OUTCOME_METHOD',
    'PrincipalOf',
    'PRINCIPAL_MISMATCH_MESSAGE',
    'PROCESS_INSTANCE',
    'REGISTRY_FULL_MESSAGE',
    'RETRY_NOT_SENT_MESSAGE',
    'ROUND_TOKEN_PREFIX',
    'round_token_instance',
    'SESSION_ALREADY_OPEN_MESSAGE',
    'SESSION_BODY_PATH',
    'SSE_PING_INTERVAL',
    'ToolServerFactory',
    'UnknownCallError',
    'UnnegotiatedSendError',
    'with_affinity_header',
]
